// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: docs/proto/v1/analytics.proto

package analytics_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopSourcesRequest) Reset() {
	*x = GetTopSourcesRequest{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopSourcesRequest) ProtoMessage() {}

func (x *GetTopSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopSourcesRequest.ProtoReflect.Descriptor instead.
func (*GetTopSourcesRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopSourcesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type SourceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	TotalEvents   uint64                 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStats) Reset() {
	*x = SourceStats{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStats) ProtoMessage() {}

func (x *SourceStats) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStats.ProtoReflect.Descriptor instead.
func (*SourceStats) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *SourceStats) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SourceStats) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type SourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*SourceStats         `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceResponse) Reset() {
	*x = SourceResponse{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceResponse) ProtoMessage() {}

func (x *SourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceResponse.ProtoReflect.Descriptor instead.
func (*SourceResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *SourceResponse) GetStats() []*SourceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_docs_proto_v1_analytics_proto protoreflect.FileDescriptor

const file_docs_proto_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1ddocs/proto/v1/analytics.proto\x12\fanalytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x14GetTopSourcesRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"H\n" +
	"\vSourceStats\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x04R\vtotalEvents\"A\n" +
	"\x0eSourceResponse\x12/\n" +
	"\x05stats\x18\x01 \x03(\v2\x19.analytics.v1.SourceStatsR\x05stats2\xb0\x01\n" +
	"\x10AnalyticsService\x12S\n" +
	"\x0fSourceTopEvents\x12\".analytics.v1.GetTopSourcesRequest\x1a\x1c.analytics.v1.SourceResponse\x12G\n" +
	"\fSourceEvents\x12\x19.analytics.v1.SourceStats\x1a\x1c.analytics.v1.SourceResponseB\x1bZ\x19pulse/api/pb/analytics_v1b\x06proto3"

var (
	file_docs_proto_v1_analytics_proto_rawDescOnce sync.Once
	file_docs_proto_v1_analytics_proto_rawDescData []byte
)

func file_docs_proto_v1_analytics_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_analytics_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_analytics_proto_rawDesc), len(file_docs_proto_v1_analytics_proto_rawDesc)))
	})
	return file_docs_proto_v1_analytics_proto_rawDescData
}

var file_docs_proto_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_docs_proto_v1_analytics_proto_goTypes = []any{
	(*GetTopSourcesRequest)(nil),  // 0: analytics.v1.GetTopSourcesRequest
	(*SourceStats)(nil),           // 1: analytics.v1.SourceStats
	(*SourceResponse)(nil),        // 2: analytics.v1.SourceResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_docs_proto_v1_analytics_proto_depIdxs = []int32{
	3, // 0: analytics.v1.GetTopSourcesRequest.since:type_name -> google.protobuf.Timestamp
	1, // 1: analytics.v1.SourceResponse.stats:type_name -> analytics.v1.SourceStats
	0, // 2: analytics.v1.AnalyticsService.SourceTopEvents:input_type -> analytics.v1.GetTopSourcesRequest
	1, // 3: analytics.v1.AnalyticsService.SourceEvents:input_type -> analytics.v1.SourceStats
	2, // 4: analytics.v1.AnalyticsService.SourceTopEvents:output_type -> analytics.v1.SourceResponse
	2, // 5: analytics.v1.AnalyticsService.SourceEvents:output_type -> analytics.v1.SourceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_analytics_proto_init() }
func file_docs_proto_v1_analytics_proto_init() {
	if File_docs_proto_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_analytics_proto_rawDesc), len(file_docs_proto_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_analytics_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_analytics_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_analytics_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_analytics_proto = out.File
	file_docs_proto_v1_analytics_proto_goTypes = nil
	file_docs_proto_v1_analytics_proto_depIdxs = nil
}
