// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: docs/proto/v1/analytics.proto

package analytics_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopSourcesRequest) Reset() {
	*x = GetTopSourcesRequest{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopSourcesRequest) ProtoMessage() {}

func (x *GetTopSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopSourcesRequest.ProtoReflect.Descriptor instead.
func (*GetTopSourcesRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopSourcesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type SourceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	TotalEvents   uint64                 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStats) Reset() {
	*x = SourceStats{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStats) ProtoMessage() {}

func (x *SourceStats) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStats.ProtoReflect.Descriptor instead.
func (*SourceStats) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *SourceStats) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SourceStats) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type SourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*SourceStats         `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceResponse) Reset() {
	*x = SourceResponse{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceResponse) ProtoMessage() {}

func (x *SourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceResponse.ProtoReflect.Descriptor instead.
func (*SourceResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *SourceResponse) GetStats() []*SourceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetHourlyTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHourlyTrendsRequest) Reset() {
	*x = GetHourlyTrendsRequest{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHourlyTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHourlyTrendsRequest) ProtoMessage() {}

func (x *GetHourlyTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHourlyTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetHourlyTrendsRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetHourlyTrendsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type TrendStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HourBucket    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=hour_bucket,json=hourBucket,proto3" json:"hour_bucket,omitempty"`
	TotalEvents   uint64                 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendStat) Reset() {
	*x = TrendStat{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendStat) ProtoMessage() {}

func (x *TrendStat) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendStat.ProtoReflect.Descriptor instead.
func (*TrendStat) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TrendStat) GetHourBucket() *timestamppb.Timestamp {
	if x != nil {
		return x.HourBucket
	}
	return nil
}

func (x *TrendStat) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type GetHourlyTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trends        []*TrendStat           `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHourlyTrendsResponse) Reset() {
	*x = GetHourlyTrendsResponse{}
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHourlyTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHourlyTrendsResponse) ProtoMessage() {}

func (x *GetHourlyTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHourlyTrendsResponse.ProtoReflect.Descriptor instead.
func (*GetHourlyTrendsResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetHourlyTrendsResponse) GetTrends() []*TrendStat {
	if x != nil {
		return x.Trends
	}
	return nil
}

var File_docs_proto_v1_analytics_proto protoreflect.FileDescriptor

const file_docs_proto_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1ddocs/proto/v1/analytics.proto\x12\fanalytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x14GetTopSourcesRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"H\n" +
	"\vSourceStats\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x04R\vtotalEvents\"A\n" +
	"\x0eSourceResponse\x12/\n" +
	"\x05stats\x18\x01 \x03(\v2\x19.analytics.v1.SourceStatsR\x05stats\"J\n" +
	"\x16GetHourlyTrendsRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"k\n" +
	"\tTrendStat\x12;\n" +
	"\vhour_bucket\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"hourBucket\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x04R\vtotalEvents\"J\n" +
	"\x17GetHourlyTrendsResponse\x12/\n" +
	"\x06trends\x18\x01 \x03(\v2\x17.analytics.v1.TrendStatR\x06trends2\xc4\x01\n" +
	"\x10AnalyticsService\x12P\n" +
	"\fGetTopSource\x12\".analytics.v1.GetTopSourcesRequest\x1a\x1c.analytics.v1.SourceResponse\x12^\n" +
	"\x0fGetHourlyTrends\x12$.analytics.v1.GetHourlyTrendsRequest\x1a%.analytics.v1.GetHourlyTrendsResponseB\x1bZ\x19pulse/api/pb/analytics_v1b\x06proto3"

var (
	file_docs_proto_v1_analytics_proto_rawDescOnce sync.Once
	file_docs_proto_v1_analytics_proto_rawDescData []byte
)

func file_docs_proto_v1_analytics_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_analytics_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_analytics_proto_rawDesc), len(file_docs_proto_v1_analytics_proto_rawDesc)))
	})
	return file_docs_proto_v1_analytics_proto_rawDescData
}

var file_docs_proto_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_docs_proto_v1_analytics_proto_goTypes = []any{
	(*GetTopSourcesRequest)(nil),    // 0: analytics.v1.GetTopSourcesRequest
	(*SourceStats)(nil),             // 1: analytics.v1.SourceStats
	(*SourceResponse)(nil),          // 2: analytics.v1.SourceResponse
	(*GetHourlyTrendsRequest)(nil),  // 3: analytics.v1.GetHourlyTrendsRequest
	(*TrendStat)(nil),               // 4: analytics.v1.TrendStat
	(*GetHourlyTrendsResponse)(nil), // 5: analytics.v1.GetHourlyTrendsResponse
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_docs_proto_v1_analytics_proto_depIdxs = []int32{
	6, // 0: analytics.v1.GetTopSourcesRequest.since:type_name -> google.protobuf.Timestamp
	1, // 1: analytics.v1.SourceResponse.stats:type_name -> analytics.v1.SourceStats
	6, // 2: analytics.v1.GetHourlyTrendsRequest.since:type_name -> google.protobuf.Timestamp
	6, // 3: analytics.v1.TrendStat.hour_bucket:type_name -> google.protobuf.Timestamp
	4, // 4: analytics.v1.GetHourlyTrendsResponse.trends:type_name -> analytics.v1.TrendStat
	0, // 5: analytics.v1.AnalyticsService.GetTopSource:input_type -> analytics.v1.GetTopSourcesRequest
	3, // 6: analytics.v1.AnalyticsService.GetHourlyTrends:input_type -> analytics.v1.GetHourlyTrendsRequest
	2, // 7: analytics.v1.AnalyticsService.GetTopSource:output_type -> analytics.v1.SourceResponse
	5, // 8: analytics.v1.AnalyticsService.GetHourlyTrends:output_type -> analytics.v1.GetHourlyTrendsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_analytics_proto_init() }
func file_docs_proto_v1_analytics_proto_init() {
	if File_docs_proto_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_analytics_proto_rawDesc), len(file_docs_proto_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_analytics_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_analytics_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_analytics_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_analytics_proto = out.File
	file_docs_proto_v1_analytics_proto_goTypes = nil
	file_docs_proto_v1_analytics_proto_depIdxs = nil
}
